services:
  postgres:
    image: postgres:17.5
    container_name: finance-tracker-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=finance_tracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changemeinprod
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
